Mag gloves
frosty-dev/ss14-core pull request #147
Opened 2024-02-29 15:15 UTC by OmntnsV

# Описание PR 

## Чек-лист:

- [x] Rechecked all my code

## typo:

- [x] Feature
- [ ] Fix
- [ ] Tweak
- [ ] Balance

**Изменения**

Добавлены магнитные перчатки для СБ. Можно изучить в ветке СБ. Базовые доступны с 2‑го уровня, а продвинутые - с 3‑го.

**Changelog**

- add: Магнитные и продвинутые магнитные перчатки

2024-03-01 01:58 UTC, Remuchi requested changes
![image](https://github.com/frosty-dev/ss14-core/assets/72476615/618a886a-fe82-450b-b13f-4c6bbf70ed80)
Есть критические баги и замечания. Скриншот сверху тому пример.
* Перчатки сами не выключаются, а время идёт в хер пойми куда
* Перчатки можно бесконечно включать, но нельзя отключить.
* При включении отсутствует попап или хотя бы какое-то уведомление о том, что перчатки включены/выключены
* Включеные перчатки игрок может сам снять со своих рук, что немного не логично.
* При снятии улучшенных магнитных перчаток - все ещё нельзя дизармить человека и воровать у него перчатки/вещи из рук.
* Перчатки защищают от любого дизарма, хотя должны защищать только от выбивания оружия из рук. Дизарм по стамине они не должны предотвращать.

2024-03-01 01:58 UTC, Remuchi commented on Resources/Locale/ru-RU/White/magnetic-gloves.ftl
> +maggloves-ready-in = Перчатки будут готовы к использованию через
Переводов экшенов нет

2024-03-01 01:58 UTC, Remuchi commented on Content.Server/Standing/StandingStateSystem.cs
> +                if (!_handsSystem.TryDrop(uid, hand, null, checkActionBlocker: false, handsComp: handsComp) && HasComp<KeepItemsOnFallComponent>(uid))
Зачем здесь ещё раз проверка на компонент `KeepItemsOnFallComponent`?
Сначала ты проверяешь, нету ли компонента на носителе, а потом проверяешь, есть ли он.

2024-03-01 01:58 UTC, Remuchi commented on Content.Server/_White/MagGloves/MagneticGlovesSystem.cs
> +                continue;
у тебя в query и так получается компонент `MagneticGlovesComponent gloves`, зачем ты его потом ещё раз получаешь у каждого энтити?

2024-03-01 01:58 UTC, Remuchi commented on Resources/Locale/en-US/white/magnetic-gloves.ftl
> +maggloves-charge = Gloves battery charge:
мне кажется этого уже тут не должно быть. Зато поля `maggloves-ready` и `maggloves-ready-in` отсутствуют

2024-03-01 01:58 UTC, Remuchi commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
> +      - ClothingHandsGlovesMagneticAdvanced
В охранный техфаб их, а не в обычный

2024-03-06 23:01 UTC, OmntnsV commented
- Исправлено
- Теперь можно
- Теперь есть
- Теперь, когда игрок их снимает, они выключаются
- Исправлено
- Исправлено

2024-03-11 04:56 UTC, RavMorgan commented
Я пиздатый, ахуеный, современный, невъебенный
Шел отдельно, без системы прямо к цели, я бесценен
Цепь танцует вальс на теле, твоя сука на прицеле
Грязный Морти возьмет Грэмми, черт возьми, я стану первым

2024-03-21 00:08 UTC, merged