[Feature] Модули для оружия
frosty-dev/ss14-core pull request #222
Opened 2024-03-20 17:21 UTC by withcodevz

# Описание PR 
Модули для оружия. Улучшенный, продвинутый, модульный фонарик, пламегаситель и глушитель.
## Скриншоты

## Чек-лист:

- [x] Rechecked all my code

## typo:

- [x] Feature
- [ ] Fix
- [ ] Tweak
- [ ] Balance

**Изменения**

**Changelog**

:cl: CaypenNow
- add: Добавлены модули для оружия. Доступны в техфабе СБ.

2024-03-21 15:10 UTC, Aviu00 reviewed
Исправишь эти замечания, и можно будет дальше ревьюить.

2024-03-21 15:10 UTC, Aviu00 commented on Content.Server/_White/WeaponModules/WeaponModulesSystem.cs
> +    }
Названия методов пишутся с большой буквы, вместо этого switch стейтмента можно сделать:
```
if(!comp.Modules.Contains(module))
   comp.Modules.Add(module);
```

2024-03-21 15:10 UTC, Aviu00 commented on Content.Server/_White/WeaponModules/WeaponModulesComponent.cs
> +    public List<string?> Modules = new();
А почему тут `string` nullable?

2024-03-21 15:10 UTC, Aviu00 commented on Content.Server/_White/WeaponModules/WeaponModulesSystem.cs
> +        }
Тут аналогично `switch` можно убрать

2024-03-21 15:10 UTC, Aviu00 commented on Content.Server/_White/WeaponModules/WeaponModulesSystem.cs
> +    private float oldFireRate;
Неправильный нейминг, приватные поля начинаются с нижнего подчеркивания и маленькой буквы.

2024-03-21 15:10 UTC, Aviu00 commented on Content.Server/_White/WeaponModules/WeaponModulesSystem.cs
> +        oldFireRate = gunComp.FireRate;
`TryComp` возвращает `true`, если компонент есть и `false` если его нет, стоит делать на это проверку вместо восклицательных знаков.

2024-03-21 15:10 UTC, Aviu00 commented on Content.Server/_White/WeaponModules/WeaponModulesSystem.cs
> +        moduleEffect(module, weapon);
Я бы сделал по другому, вместо `switch` стейтментов внутри этих методов можно сделать дочерние компоненты от компонента с именем по типу `BaseWeaponModuleComponent`, в которых будут свои данные, к примеру компонент отвечающий за модуль, увеличивающий скорость стрельбы, там будет хранится эта скорость стрельбы и `oldFireRate`. Сейчас `oldFireRate` хранится почему-то в системе, то есть он глобальный для всех оружий. В итоге мы имеем компонент с именем по типу `FireRateModifyModuleComponent`, наследуемый от `BaseWeaponModuleComponent`. И мы имеем `SubscribeLocalEvent<FireRateModifyModuleComponent, EntInsertedIntoContainerMessage>(OnFireRateModuleInsert)`, где будет то, что сейчас находится в `switch` стейтментах в этих двух методах. Аналогично с ремувом.

2024-03-21 15:10 UTC, Aviu00 commented on Content.Server/_White/WeaponModules/WeaponModulesSystem.cs
> +    }
А лучше убрать этот метод и сделать, как я писал выше.

2024-03-21 15:10 UTC, Aviu00 commented on Content.Shared/Weapons/Ranged/Components/GunComponent.cs
> +    public bool canUseEffect;
Публичное поле с большой буквы

2024-03-21 15:10 UTC, Aviu00 commented on Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.cs
> +        var attemptEv = new GunMuzzleFlashAttemptEvent(gunComponent!.canUseEffect); // WD EDIT
Не ставь `Cancelled` в ивенте так вот просто. Вместо этого нужно подписаться на ивент через компонент `WeaponModulesComponent` и проверить на наличие пламегасителя. И, получается, поле `canUseEffect` в `GunComponent` не нужно вовсе.

2024-03-21 15:10 UTC, Aviu00 commented on Content.Server/_White/WeaponModules/WeaponModulesComponent.cs
> +    public List<string?> Modules = new();
А вообще лучше хранить список ентити, а не строк, ведь модули оружия это ентити.

2024-03-21 15:10 UTC, Aviu00 commented on Content.Server/_White/WeaponModules/WeaponModulesSystem.cs
> +        oldFireRate = gunComp.FireRate;
В других подобных местах аналогичное замечание

2024-03-22 10:27 UTC, ThereDrD0 commented
После того как пофиксишь код - напиши, я по дизайну фичи скажу, что можно добавить. Звуки там или какой-то QoL

2024-03-24 09:11 UTC, Aviu00 requested changes
Хотелось бы иметь больше одного слота модуля под оружие. Для этого можно `ModulesSlot` вынести из системы в `DataField` `BaseModuleComponent` и сделать несколько слотов с разным назанием. Ну и с `WeaponModulesVisuals` надо будет пошаманить для этого.

2024-03-24 09:11 UTC, Aviu00 commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/SMGs/smgs.yml
> +        map: [ "enum.ModuleVisualState.Module" ]
Нужно добавить поле `visible: false` вместо `args.Sprite.LayerSetVisible(ModuleVisualState.Module, false);` в системе `WeaponModulesVisuals`

2024-03-24 09:11 UTC, Aviu00 commented on Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.cs
> +    public void setSound(EntityUid weapon, SoundSpecifier sound)
Методы с большой буквы. Вообще лучше не срать в код оффов и перенести эти методы из этой системы.

2024-03-24 09:11 UTC, Aviu00 commented on Content.Server/_White/WeaponModules/WeaponModulesSystem.cs
> +            weaponModulesComponent.Modules.Add(module);
Эти строчки кучу раз повторяются, можно перенести в метод `bool TryInsertWeaponModule(...)`, чтобы не дублировалось. Аналогично с вытаскиванием.

2024-03-24 09:11 UTC, Aviu00 commented on Content.Server/_White/WeaponModules/WeaponModulesSystem.cs
> +        _gunSystem.setFireRate(weapon, 7.5F);
7.5 магическое число, лучше сделать это чесло датафилдом компонента `AcceleratorModule`, так могут быть несколько модулей, дающих разный фаеррейт. А вобще вместо установки значения фаеррейта лучше давать +1 или +2 и тд в зависимости от модуля.

2024-03-24 09:11 UTC, Aviu00 commented on Content.Server/_White/WeaponModules/WeaponModulesSystem.cs
> +        _appearanceSystem.SetData(weapon, ModuleVisualState.Module, "light", appearanceComponent);
Эти строчки тоже можно перенести в тот же метод `TryInsertWeaponModule`, "light" сделать датафилдом компонента.

2024-03-24 09:11 UTC, Aviu00 commented on Content.Server/_White/WeaponModules/WeaponModulesSystem.cs
> +        _gunSystem.setProjectileSpeed(weapon, 35.5F);
35.5 вынести в датафилд компонента, вообще все подобные числа вынести. Надо сделать то же самое, что я писал касательно фаеррейта.

2024-03-24 09:11 UTC, Aviu00 commented on Content.Server/_White/WeaponModules/WeaponModulesSystem.cs
> +        _gunSystem.setProjectileSpeed(weapon, 25F);
А что если у оружия была скорость выстрела не 25?

2024-03-24 09:11 UTC, Aviu00 commented on Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.cs
> +        gunComponent!.SoundGunshot = sound;
Сделать проверку на `TryComp` и убрать восклицательный знак. Тут и в других методах.

2024-03-24 09:11 UTC, Aviu00 commented on Content.Shared/_White/WeaponModules/SharedWeaponModulesSystem.cs
> +}
Можно это убрать.

2024-03-24 12:00 UTC, Aviu00 commented on Content.Server/_White/WeaponModules/WeaponModulesSystem.cs
> +        if(!TryEjectModule(module, weapon, args) || !TryComp<WeaponModulesComponent>(weapon, out var weaponModulesComponent))
У тебя в методе `TryEjectModule` уже проверяется `TryComp<WeaponModulesComponent>`, можно вместо повторной проверки добавить в аргументы метода `[NotNullWhenTrue] out WeaponModulesComponent? weaponModulesComponent`

2024-03-25 05:40 UTC, Aviu00 requested changes

2024-03-25 05:40 UTC, Aviu00 commented on Content.Server/_White/WeaponModules/WeaponModulesSystem.cs
> +    }
```suggestion
    private bool TryInsertModule(EntityUid module, EntityUid weapon, BaseModuleComponent component,
        EntGotInsertedIntoContainerMessage args, [NotNullWhen(true)] out WeaponModulesComponent? weaponModulesComponent,
        [NotNullWhen(true)] out AppearanceComponent? appearanceComponent)
    {
        if (!TryComp(weapon, out weaponModulesComponent) || !TryComp(weapon, out appearanceComponent) ||
            ModulesSlot != args.Container.ID)
        {
            weaponModulesComponent = null;
            appearanceComponent = null;
            return false;
        }
        
        if(!weaponModulesComponent.Modules.Contains(module))
            weaponModulesComponent.Modules.Add(module);

        _appearanceSystem.SetData(weapon, ModuleVisualState.Module, component.AppearanceValue, appearanceComponent);
        
        return true;
    }
```
Аналогично с вытаскиванием. Но с вытаскиванием не нужно передавать в аргументы `BaseModuleComponent`, получается. По крайней мере пока у нас один модуль на оружие.

2024-03-25 05:40 UTC, Aviu00 commented on Content.Server/_White/WeaponModules/WeaponModulesSystem.cs
> +    }
Это убираем.

2024-03-25 05:40 UTC, Aviu00 commented on Content.Server/_White/WeaponModules/WeaponModulesSystem.cs
> +        _gunSystem.SetFireRate(weapon, component.OldFireRate + 2F);
2F вынести в датафилд компонента.

2024-03-25 05:40 UTC, Aviu00 commented on Content.Server/_White/WeaponModules/WeaponModulesSystem.cs
> +        _gunSystem.SetProjectileSpeed(weapon, component.OldProjectileSpeed + 15F);
15F вынести в датафилд компонента.

2024-03-25 05:40 UTC, Aviu00 commented on Content.Server/_White/WeaponModules/WeaponModulesSystem.cs
> +        _lightSystem.SetRadius(weapon, 4F, light);
Радиус тоже можно датафилдом компонента сделать.

2024-03-25 05:40 UTC, Aviu00 commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Rifles/rifles.yml
> +  - type: WeaponModulesVisuals
Этого компонента, кажется, больше не существует. Можно убрать отовсюду.

2024-03-25 05:40 UTC, Aviu00 commented on Resources/Prototypes/_White/Entities/Objects/Weapons/Guns/Modules/modules.yml
> +  description: Light module for rifles (lector, CV, drozd, WT).
Оно называется lecter.

2024-03-25 09:50 UTC, Aviu00 approved these changes

2024-03-25 13:39 UTC, Remuchi requested changes
В целом вопрос по дизайну. Вот есть у нас условный модуль фонарик. Как я понимаю, его можно прикрепить только на винтовки и ПП. Почему же нельзя тогда на пистолет? Я думаю, было бы неплохо сделать какой-нибудь условный блеклист/вайтлист тогда модулей. И добавить модули уже на пистолеты и дробовики.

Так же хотелось бы, чтобы оружие с модулями при осмотре было видно, какие модули установлены.

2024-03-25 13:39 UTC, Remuchi commented on Content.Server/_White/WeaponModules/WeaponModulesSystem.cs
> +
логично будет вынести эту проверку выше, чем `TryInsertModule`
Во-первых, более дешевая (более дешевые проверки всегда должны быть выше более дорогих)
Во-вторых, логичней предположить, что мы сначала проверим, является ли ентити оружием, прежде чем будем крепить оружейный модуль на ентити

2024-03-25 13:39 UTC, Remuchi commented on Content.Server/_White/WeaponModules/WeaponModulesSystem.cs
> +            ModulesSlot != args.Container.ID)
1. Тебе нет смысла передавать сюда все `EntGotInsertedIntoContainerMessage args` ибо ты используешься только `args.Container.ID`. Передавай напрямую `string containerId`. А ещё с точки зрения логики будет правильнее проверять `containerId != ModulesSlot`, а не наоборот
2. `out AppearanceComponent? appearanceComponent` у тебя этот параметр используется ровно один раз, в модуле фонарика. Вместо того, чтобы делать его `out`, лучше сделай его как обычный параметр изначально с `appearanceComponent = null`, и получай его уже в этом методе, если он не был передан.

2024-03-25 13:39 UTC, Remuchi commented on Content.Server/_White/WeaponModules/WeaponModulesSystem.cs
> +    private bool TryEjectModule(EntityUid module, EntityUid weapon, EntGotRemovedFromContainerMessage args, [NotNullWhen(true)] out WeaponModulesComponent? weaponModulesComponent, [NotNullWhen(true)]
здесь `out AppearanceComponent? appearanceComponent` вообще нигде дальше не используется

2024-03-25 13:39 UTC, Remuchi commented on Content.Server/_White/WeaponModules/WeaponModulesSystem.cs
> +        weaponModulesComponent.UseEffect = true;
Честно я вообще по названию не могу понять, что тут происходит. `UseEffect` мне не даёт никакого представления о том, за что это поле должно отвечать

2024-03-25 13:39 UTC, Remuchi commented on Content.Server/_White/WeaponModules/WeaponModulesSystem.cs
> +        if (!TryComp<GunComponent>(weapon, out var gunComp)) return;
аналогично выше

2024-03-25 13:39 UTC, Remuchi commented on Content.Server/_White/WeaponModules/WeaponModulesSystem.cs
> +        if (!TryComp<GunComponent>(weapon, out var gunComp)) return;
аналогично выше

2024-03-25 13:39 UTC, Remuchi commented on Content.Server/_White/WeaponModules/WeaponModulesSystem.cs
> +        _lightSystem.TryGetLight(weapon, out var light);
Ты же знаешь что `EnsureLight` возвращает как раз таки `SharedPointLightComponent`, который ты пытаешься получить дальше в `TryGetLight`?

2024-03-25 13:39 UTC, Remuchi commented on Content.Server/_White/WeaponModules/WeaponModulesSystem.cs
> +        _lightSystem.TryGetLight(weapon, out var light);
Если используешься `Try...`, то оберни в `if`. Мало ли этого компонента по итогу не окажется на оружии, каким-либо образом.
А вообще я бы просто удаляла компонент `PointLight` с оружия вместо этого. Нечего оружию иметь компоненты, которые уже никак не используются

2024-03-25 13:39 UTC, Remuchi commented on Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.cs
> +        if(cancelled) return;
У тебя на это есть прямо отдельный ивент, который вызывается ниже - `GunMuzzleFlashAttemptEvent`. Не надо это пихать напрямую в основной метод. Подвязывай тот ивент к своему компоненту и проверяй там.

2024-03-25 13:39 UTC, Remuchi commented on Content.Shared/_White/WeaponModules/AcceleratorModuleComponent.cs
> +    [ViewVariables(VVAccess.ReadWrite), DataField]
зачем тут `ReadWrite` и `DataField`. ДатаФилд не нужно ибо это не используется в прототипе

2024-03-25 13:39 UTC, Remuchi commented on Content.Shared/_White/WeaponModules/LaserModuleComponent.cs
> +    [ViewVariables(VVAccess.ReadWrite), DataField]
Аналогично замечанию в `AcceleratorModule`

2024-03-25 13:39 UTC, Remuchi commented on Content.Shared/_White/WeaponModules/SilencerModuleComponent.cs
> +    [ViewVariables(VVAccess.ReadWrite), DataField]
Аналогично замечаниям выше

2024-03-25 13:39 UTC, Remuchi commented on Resources/Locale/ru-RU/locales-new/autotranslate-57.ftl
> +  .desc = Улучшенный модуль. Увеличивает скорость ваших пуль.
В чем улучшенные модули отличаются от не улучшенных? Существование улучшенного лазерного модуля должно подразумевать под собой существование обычного лазерного модуля

2024-03-25 13:39 UTC, Remuchi commented on Resources/Locale/ru-RU/locales-new/autotranslate-57.ftl
> +  .desc = Увеличивает скорострельность оружия.
А как его `продвинутость` связана с увеличением скорострельности оружия?

2024-03-25 13:39 UTC, Remuchi commented on Resources/Prototypes/_White/Entities/Objects/Weapons/Guns/Modules/modules.yml
> +  - type: Item
а зачем тут ты даешь снова компонент `Item` никак его не переопределяя, если он есть уже у родительского `BaseModule`?

2024-03-25 13:39 UTC, Remuchi commented on Resources/Prototypes/_White/Entities/Objects/Weapons/Guns/Modules/modules.yml
> +  - type: Item
аналогично выше

2024-03-25 13:39 UTC, Remuchi commented on Resources/Prototypes/_White/Entities/Objects/Weapons/Guns/Modules/modules.yml
> +  - type: Item
аналогично выше

2024-03-25 13:39 UTC, Remuchi commented on Resources/Prototypes/_White/Entities/Objects/Weapons/Guns/Modules/modules.yml
> +  - type: Item
аналогично выше

2024-03-25 13:39 UTC, Remuchi commented on Resources/Prototypes/_White/Entities/Objects/Weapons/Guns/Modules/modules.yml
> +  - type: Item
аналогично выше

2024-03-29 20:33 UTC, merged