Новые штуки в автозамену
frosty-dev/ss14-core pull request #24
Opened 2024-02-02 15:45 UTC by ThereDrD0

# Описание PR 
Убрал негров и пидорасов из автозамены, потому что бесполезная бесящая замена. 
Убрал замену сокращений глав, потому что невозможно такой заменой покрыть все случаи использования
## Скриншоты

## Чек-лист:

- [x] Rechecked all my code

## typo:

- [ ] Feature
- [ ] Fix
- [x] Tweak
- [ ] Balance

**Изменения**

**Changelog**

:cl: ThereDrD
- tweak: Убрана автозамена на сокращения глав и традиционные русские ругательства.

2024-02-03 10:54 UTC, rhailrake requested changes

2024-02-03 10:54 UTC, rhailrake commented on Resources/White/ChatFilters/slang.json
> -    "куколдов": "оленей"
nope

2024-02-04 11:05 UTC, EnefFlow commented on Resources/White/ChatFilters/slang.json
> -    "куколдов": "оленей"
Сделали для стримеров, пока альтернативы нет, так что зачем убирать???

2024-02-04 14:00 UTC, ThereDrD0 commented on Resources/White/ChatFilters/slang.json
> -    "куколдов": "оленей"
Я сделаю кнопку педалям, но эта замена хуета полная, а у нас ровно 0 стримеров.

2024-02-06 15:40 UTC, closed without merging