[Feature] Экспериментальный телепортер синдиката
frosty-dev/ss14-core pull request #250
Opened 2024-03-27 23:42 UTC by withcodevz

# Описание PR 
Телепортирует вперед рандомно на 3-8 тайла, в случае если на конечном тайле стена - использует экстренную телепортацию (телепорт на 3 тайла в любом направлении), если на тайле экстренной телепортации стена - гибает. Телепортер взят с сс13.
## Скриншоты

## Чек-лист:

- [x] Rechecked all my code

## typo:

- [x] Feature
- [ ] Fix
- [ ] Tweak
- [ ] Balance

**Изменения**

**Changelog**

:cl: CaypenNow
- add: Экспериментальный телепортер синдиката

2024-03-31 06:43 UTC, Remuchi requested changes

2024-03-31 06:43 UTC, Remuchi commented on Content.Server/_White/ExperimentalSyndicateTeleporter/ExperimentalSyndicateTeleporter.cs
> +        }, comp.CancelTokenSource.Token);
Используй `Update` вместо того, чтобы клепать миллион таймеров

2024-03-31 06:43 UTC, Remuchi commented on Content.Server/_White/ExperimentalSyndicateTeleporter/ExperimentalSyndicateTeleporter.cs
> +        int random = new Random().Next(component.MinTeleportRange, component.MaxTeleportRange);
Не создавай каждый раз новый инстанс рандома. Используй `IRobustRandom`

2024-03-31 06:43 UTC, Remuchi commented on Content.Server/_White/ExperimentalSyndicateTeleporter/ExperimentalSyndicateTeleporter.cs
> +
Почему некоторые у тебя переменные создаются через `var`, другие через прямое указание типа данных? Либо так, либо так, не делай мешанину. Желательно использовать `var`

2024-03-31 06:43 UTC, Remuchi commented on Content.Server/_White/ExperimentalSyndicateTeleporter/ExperimentalSyndicateTeleporter.cs
> +        int randomRotation = new Random().Next(0, component.RandomRotations.Count);
используй `IRobustRandom`

2024-03-31 06:43 UTC, Remuchi commented on Resources/Prototypes/_White/Catalog/uplink.yml
> +  description: Телепортер синдиката, при использовании перемещает на 3-8 метров вперед. В случае телепортации в стену, использует экстренную телепортацию. Имеет 4 заряда и автоматически заряжается.
здесь не должно быть на русском изначально. Используй fluent

2024-03-31 06:55 UTC, Remuchi commented
Еще. Не знаю, баг или фича, но телепорт идет в сторону куда смотрит персонаж, а не куда наведен курсор. Я бы сказала, что это баг

2024-04-01 06:19 UTC, withcodevz commented
> Еще. Не знаю, баг или фича, но телепорт идет в сторону куда смотрит персонаж, а не куда наведен курсор. Я бы сказала, что это баг

Фича из тринашки

2024-04-01 08:51 UTC, merged